{% set name = "pandocfilters" %}
{% set version = "1.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pandocfilters-{{ version }}.tar.gz
  sha256: 0b679503337d233b4339a817bfc8c50064e2eff681314376a47cb582305a7a38

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - pandocfilters
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jgm/pandocfilters
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'A python module for writing pandoc filters'
  dev_url: https://github.com/jgm/pandocfilters

extra:
  recipe-maintainers:
    - ickc
    - minrk
