{% set name = "pandocfilters" %}
{% set version = "1.5.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pandocfilters-{{ version }}.tar.gz
  sha256: 002b4a555ee4ebc03f8b66307e287fa492e4a77b4ea14d3f934328297bb4939e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python !=3.0,!=3.1,!=3.2,!=3.3
  run:
    - python !=3.0,!=3.1,!=3.2,!=3.3

test:
  imports:
    - pandocfilters
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jgm/pandocfilters
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'A python module for writing pandoc filters'
  dev_url: https://github.com/jgm/pandocfilters

extra:
  recipe-maintainers:
    - ickc
    - minrk
