{% set name = "pandocfilters" %}
{% set version = "1.5.0" %}
{% set sha256 = "0b679503337d233b4339a817bfc8c50064e2eff681314376a47cb582305a7a38" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - pandocfilters

about:
  home: https://github.com/jgm/pandocfilters
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A python module for writing pandoc filters

  dev_url: https://github.com/jgm/pandocfilters

extra:
  recipe-maintainers:
    - minrk
