{% set name = "pandocfilters" %}
{% set version = "1.4.2" %}
{% set sha256 = "b3dd70e169bb5449e6bc6ff96aea89c5eea8c5f6ab5e207fc2f521a2cf4a0da9" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - pandocfilters

about:
  home: https://github.com/jgm/pandocfilters
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A python module for writing pandoc filters'

  dev_url: https://github.com/jgm/pandocfilters

extra:
  recipe-maintainers:
    - minrk
