schema_version: 1

context:
  version: "1.5.0"

package:
  name: pandocfilters
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/p/pandocfilters/pandocfilters-${{ version }}.tar.gz
  sha256: 0b679503337d233b4339a817bfc8c50064e2eff681314376a47cb582305a7a38

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - pandocfilters
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A python module for writing pandoc filters
  homepage: https://github.com/jgm/pandocfilters
  repository: https://github.com/jgm/pandocfilters

extra:
  recipe-maintainers:
    - ickc
    - minrk
    - mgorny
