travis:
  secure:
    BINSTAR_TOKEN: GDY6YDVjvkXEHlds2YINnzNo6MD0CgN6o0JZJupmd651F3IyXVZRe+Q64H+ROcVK2Wz4IvplJU3YVHU27AIyu6zF+82Y8bgH7xIWykzQ0EsThdiyXxVStaiZjMur/VZsJx8pptREmegt836t+OTxDXV+KJemkSdq7Sn9OnfVyalsP8v8Kl5J5f8uwcZCoRb3kQe6QP3zjeM+FX1sY3CeTOCDSuDLIaZjqxLI5xJYu4GAg7xWYXEpaJdgP4LCKp/S3hxycDJAfd4YYfmkj6E4QosBc0OddYOWwqzUDPvfoqb3rRjqRDZmZTwhAq+xYcP9VZlE5saj/qlCY0dzqDoK/Cy2dKBUsi6VURmek9avjpeVCdsGfNSFXRNMF3Si7O6pLGRyP6EgrYOqPtgu+k7+jtQyRJQEkfuxghAI59ZxGocWnQ5SVdwhk03WrbbvjFgmEupYne7tsNULOUYvuYOwFgKtK6ebspOCQQhRwir2Sqlrlz2nyjhAGTYJnrCjXkFgFotR1IqwkotPrKc+/nhrxO+kxEa9OPvkz67jfiZn+xrSH+5ppFl8V2g3ZeSTr8bxSFswqpbSX5T7SZnwjFHkKQ3na0P8B7eK1gNVr66d2M/Hd75QzLkPLLTUhvnD3jlRxQ9a5WTwFOPZkwdDqOxfOZBElxIQRffNtNe/CDt5oxg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
