travis:
  secure:
    BINSTAR_TOKEN: MG3uErvDCm9nsMAn7Yiauvwc2zRQs3cf5mWxwhQGlbQiHvSS1PNpy2nRptpN95/k5ObPRUS+7iCfil8ZcMAfpa8ELj5u5oDSKhq66UAHUnzwJkss+9wKOnJuRFxAI2wEre19HbazmRcBE7R3+cVpWec0yNMAUgrEXP1/NL8ZkBm4uv7xEoU9RsmwmyXynXgaGrMfbr2hKedki4Cjom8CFVQk4iBJgJIbfzC9UzReHr+Ss9jnOkryjBvPccDJjYQryxcm6U37acK/C8lDVtuUjqNu5vnKG00KpSZfUkErFywYxpG6cj8A9+07REkhEgclpzVDasZQzD/H+pivAMtG1eWPkH1uSSASXzg6GlbKzwKKSpVTExQhm4cx8Tg+h+w/W+SArV9u02IhkGP9v1sr1t9K0R8fjnnET9xjE7DiboXqeM8u36l6VpllsekfS35BqJ8ljdvg4452yC38/rToJCt0qrLXZzKbdaLGUBC5c2/3+S9xsEv6MEXbVI3powxZFsW5eQ6baLnSIRXkKoIOhU4CJMKPpG/yqvZiX6t3DQcmXhDa5gtcdSwS3UG/xuJUEyHxH5EK7hZPvcT8nx9ii4TkU9DeShiUiztFAHF576CSG7QJbvqtiowx98HHcWeh2JuNdMMeI6ZCFSKnGLa2UdSnoCaOi68KLlQCMjUikqU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
